"""
run_model.py
============
Interactive script to run Qwen3.5-0.8B via LM Studio.

100% LOCAL — No OpenAI SDK, no internet, no API keys.
Uses Python's 'requests' library to talk directly to your
LM Studio local server at http://localhost:1234

- You type a prompt and choose a category
- The model responds
- Everything is automatically saved to prompts_and_responses.md

Setup:
    1. Open LM Studio -> Load Qwen3.5-0.8B -> Start Local Server (port 1234)
    2. pip install requests
    3. python run_model.py
"""

import requests
from datetime import datetime
import time
import os
import sys

# ── Config ─────────────────────────────────────────────────────────────────
LM_STUDIO_URL = "http://localhost:1234"   # Your local LM Studio server
MODEL_NAME    = "qwen3.5-0.8b"           # Match exact name in LM Studio server tab
TEMPERATURE   = 1.2
MAX_TOKENS    = 1024
OUTPUT_FILE   = os.path.join(os.path.dirname(os.path.abspath(__file__)), "prompts_and_responses.md")
# ───────────────────────────────────────────────────────────────────────────

CATEGORIES = [
    "Coding",
    "General Knowledge / QA",
    "Reasoning",
    "Visual Question Answering",
    "Other",
]
BANNER = """
╔══════════════════════════════════════════════════════╗
║        Qwen3.5-0.8B  —  LM Studio Interface          ║
║         100% Local — No internet, No APIs            ║
║    Prompts auto-saved to prompts_and_responses.md    ║
╚══════════════════════════════════════════════════════╝
"""


def check_connection():
    """Verify LM Studio local server is running."""
    print(f"  Connecting to LM Studio at {LM_STUDIO_URL} ...", end="", flush=True)
    try:
        resp = requests.get(f"{LM_STUDIO_URL}/v1/models", timeout=5)
        resp.raise_for_status()
        print(" Connected\n")
    except Exception:
        print("\n\n  Could not connect to LM Studio.")
        print("  -> Open LM Studio -> Local Server tab -> click Start Server\n")
        sys.exit(1)


def pick_category() -> str:
    """Let the user pick a prompt category."""
    print("  Select a category:")
    for i, cat in enumerate(CATEGORIES, 1):
        print(f"    [{i}] {cat}")
    while True:
        choice = input("  Enter number (1-5): ").strip()
        if choice.isdigit() and 1 <= int(choice) <= len(CATEGORIES):
            return CATEGORIES[int(choice) - 1]
        print("  Invalid choice, try again.")


def query_model(prompt: str) -> tuple:
    """
    Send a prompt directly to LM Studio via a plain HTTP POST request.
    No OpenAI SDK — just requests hitting localhost.
    """
    url     = f"{LM_STUDIO_URL}/v1/chat/completions"
    payload = {
        "model": MODEL_NAME,
        "messages": [{"role": "user", "content": prompt}],
        "temperature": TEMPERATURE,
        "max_tokens": MAX_TOKENS,
    }

    start    = time.time()
    response = requests.post(url, json=payload, timeout=300)
    response.raise_for_status()
    elapsed  = round(time.time() - start, 2)

    data = response.json()
    text = data["choices"][0]["message"]["content"].strip()
    return text, elapsed


def save_to_md(category, prompt, response, elapsed, evaluation, notes):
    """Append a single prompt/response entry to the markdown file."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    entry = f"""
## [{category}] — {timestamp}

**Prompt:**
{prompt}

**Model Response:**
{response}

**Response Time:** {elapsed}s
**Evaluation:** {evaluation}
**Notes:** {notes}

---
"""
    with open(OUTPUT_FILE, "a", encoding="utf-8") as f:
        f.write(entry)

    print(f"\n  Saved to {OUTPUT_FILE}")


def init_output_file():
    """Create the markdown file with a header if it doesn't exist."""
    if not os.path.exists(OUTPUT_FILE):
        with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
            f.write("# Prompts and Responses — Qwen3.5-0.8B\n\n")
            f.write("> Auto-generated by run_model.py\n\n")
            f.write("---\n")


def main():
    print(BANNER)
    init_output_file()
    check_connection()

    print(f"  Model   : {MODEL_NAME}")
    print(f"  Temp    : {TEMPERATURE}")
    print(f"  Output  : {OUTPUT_FILE}")
    print()
    print("  Type your prompt, or type 'quit' to exit.")
    print("-" * 54)

    while True:
        print()
        category = pick_category()

        print()
        prompt = input("  Enter your prompt:\n  > ").strip()
        if prompt.lower() in ("quit", "exit", "q"):
            print(f"\n  Goodbye! All responses saved to {OUTPUT_FILE}")
            break
        if not prompt:
            print("  Empty prompt, skipping.")
            continue

        print("\n  Querying Qwen3.5-0.8B... (may take 30-90s on CPU)\n")
        try:
            response, elapsed = query_model(prompt)
        except requests.exceptions.Timeout:
            print("  Request timed out. Model may still be loading in LM Studio.")
            continue
        except Exception as e:
            print(f"  Error: {e}")
            continue

        print("-" * 54)
        print("  MODEL RESPONSE:")
        print("-" * 54)
        print(response)
        print("-" * 54)
        print(f"  Response time: {elapsed}s")

        print()
        print("  Rate the response:")
        print("    [1] Correct / Good")
        print("    [2] Partially correct")
        print("    [3] Incorrect / Hallucinated")
        print("    [4] Incomplete")
        eval_map = {
            "1": "Correct / Good",
            "2": "Partially correct",
            "3": "Incorrect / Hallucinated",
            "4": "Incomplete",
        }
        eval_choice = input("  Enter number (1-4): ").strip()
        evaluation  = eval_map.get(eval_choice, "Not rated")
        notes       = input("  Add a short note (or press Enter to skip): ").strip()
        if not notes:
            notes = "-"

        save_to_md(category, prompt, response, elapsed, evaluation, notes)

        again = input("\n  Run another prompt? (y/n): ").strip().lower()
        if again != "y":
            print(f"\n  All done! Results saved to: {OUTPUT_FILE}")
            break
        print("\n" + "-" * 54)


if __name__ == "__main__":
    main()
